[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlz"
version = "1.0.0"
description = "A Library to view mysql tables in Python, Just like how it looks in mysql."
readme = "README.md"
authors = [
  { name="Ashin Jiyo", email="ashinjiyo639@gmail.com" }
]
license = "Apache-2.0"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/Ashin-Jiyo/sqlz"